import { Router } from "express";
import { documentRoutes } from "./document.routes.js";
import { chatRoutes } from "./chat.routes.js";
import { googleAuthRoutes } from "./google-auth.routes.js";
import { gmailRoutes } from "./gmail.routes.js";
import { calendarRoutes } from "./calendar.routes.js";
import { linkedinAuthRoutes } from "./linkedin-auth.routes.js";
import { linkedinRoutes } from "./linkedin.routes.js";
import { actionsRoutes } from "./actions.routes.js";
import { sessionsRoutes } from "./sessions.routes.js";
import { authRoutes } from "./auth.routes.js";
import { agentsRoutes } from "./agents.routes.js";
import { searchRoutes } from "./search.routes.js";
import { automationsRoutes } from "./automations.routes.js";
import { githubRoutes } from "./github-auth.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRoutes);
apiRouter.use("/documents", documentRoutes);
apiRouter.use("/chat", chatRoutes);
apiRouter.use("/google", googleAuthRoutes);
apiRouter.use("/gmail", gmailRoutes);
apiRouter.use("/calendar", calendarRoutes);
apiRouter.use("/linkedin", linkedinAuthRoutes);
apiRouter.use("/linkedin", linkedinRoutes);
apiRouter.use("/actions", actionsRoutes);
apiRouter.use("/sessions", sessionsRoutes);
apiRouter.use("/agents", agentsRoutes);
apiRouter.use("/search", searchRoutes);
apiRouter.use("/automations", automationsRoutes);
apiRouter.use("/github", githubRoutes);